openapi: 3.0.0
info:
  version: 1.0.0
  title: API SERVICES
  description: API Documentation
servers:
  - url: https://gwkong.pusri.co.id/service-iam-dev
    description: API Dev
  - url: https://gwkong.pusri.co.id/service-iam-prod
    description: API Prod
  - url: http://10.10.2.189:62714
    description: API Send OTP WA

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  parameters:
    Page:
      name: page
      in: query
      description: "Page number for pagination (default: 1)"
      schema:
        type: integer
    Limit:
      name: limit
      in: query
      description: "Number of items to return per page (default: 10)"
      schema:
        type: integer

  responses:
    "200":
      description: OK
    "400":
      description: "Bad Request"
    "401":
      description: Unauthorized

security:
  - bearerAuth: []

paths:
  /api/organization:
    get:
      tags:
        - Organizations
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Limit"
        - in: query
          name: text
          schema:
            type: string
        - in: query
          name: code
          schema:
            type: string
        - in: query
          name: org_code
          schema:
            type: string
        - in: query
          name: code_parent
          schema:
            type: string
        - in: query
          name: level
          schema:
            type: string
          description: "1 Direktorat, 2 Kompartemen, 3 Departemen"
        - in: query
          name: status
          schema:
            type: string
          description: "active, in-active"
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /send-otp:
    post:
      tags:
        - Kode OTP
      description: This endpoint is used for send kode otp via wa, and it is accessible to all roles.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                badge:
                  type: string
                name:
                  type: string
                phone_number:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /verify-otp:
    post:
      tags:
        - Kode OTP
      description: This endpoint is used for verify kode, and it is accessible to all roles.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kode:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
