openapi: 3.0.0
info:
  version: 1.0.0
  title: API SERVICES
  description: API Documentation
  
servers:

  - url: http://10.10.2.189:62799
    description: API PUSRI Dev
  - url: https://gwkong.pusri.co.id/service-iam-dev
    description: API ORG Dev
  - url: http://10.10.2.189:62714
    description: API Send OTP WA
  - url: http://10.10.2.189:62821
    description: API Encrypt Decrypt

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  parameters:
    Page:
      name: page
      in: query
      description: "Page number for pagination (default: 1)"
      schema:
        type: integer

    Limit:
      name: limit
      in: query
      description: "Number of items to return per page (default: 10)"
      schema:
        type: integer

    Size:
      name: size
      in: query
      description: "Number of items to return per page"
      schema:
        type: integer

  responses:
    "200":
      description: OK
    "400":
      description: "Bad Request"
    "401":
      description: Unauthorized

security:
  - bearerAuth: []

paths:

  /api/organization:
    get:
      tags:
        - organizations
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Limit"
        - in: query
          name: text
          schema:
            type: string
        - in: query
          name: code
          schema:
            type: string
        - in: query
          name: org_code
          schema:
            type: string
        - in: query
          name: code_parent
          schema:
            type: string
        - in: query
          name: level
          schema:
            type: string
          description: "1 Direktorat, 2 Kompartemen, 3 Departemen"
        - in: query
          name: status
          schema:
            type: string
          description: "active, in-active"
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /send-otp:
    post:
      tags:
        - kode otp
      description: This endpoint is used for send kode otp via wa, and it is accessible to all roles.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                badge:
                  type: string
                name:
                  type: string
                phone_number:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /verify-otp:
    post:
      tags:
        - kode otp
      description: This endpoint is used for verify kode, and it is accessible to all roles.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kode:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/encrypt:
    post:
      tags:
        - encrypt - decrypt
      description: This endpoint is used for encrypt text, and it is accessible user role registered.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/decrypt:
    post:
      tags:
        - encrypt - decrypt
      description: This endpoint is used for decrypt text, and it is accessible user role registered.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                key:
                  type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/adm-app/analisa-lab:
    get:
      tags:
        - adm app
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string
        - in: query
          name: delivery_item
          schema:
            type: string
        - in: query
          name: nomor_material
          schema:
            type: string
        - in: query
          name: nomor_do
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
  
  /api/v1/sap/zmm_r21/purchasing:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: material_no
          schema:
            type: string
        - in: query
          name: no_pr
          schema:
            type: string
        - in: query
          name: line_item_pr
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/iw39/order:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/iw49n/order-list:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
        - in: query
          name: operation_activity
          schema:
            type: string
        - in: query
          name: description
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/iw29/notification:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/iw47/confirmation:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/zmm_r15/stock-material:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"

  /api/v1/sap/zsd_sodo_period_sales_order:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: order_no
          schema:
            type: string
        - in: query
          name: notification_no
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"        

  /api/v1/sap/zsd_sodo_pgi/sales-order:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string
        - in: query
          name: delivery_item
          schema:
            type: string
        - in: query
          name: nomor_material
          schema:
            type: string
        - in: query
          name: nomor_do
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"        

  /api/v1/sap/mb25_reservasi:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string
        - in: query
          name: delivery_item
          schema:
            type: string
        - in: query
          name: nomor_material
          schema:
            type: string
        - in: query
          name: nomor_do
          schema:
            type: string
       
      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"      

  /api/v1/sap/plant:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string

      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"   

  /api/v1/sap/equipment:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string

      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"  

  /api/v1/sap/component_bom:
    get:
      tags:
        - sap
      parameters:
        - $ref: "#/components/parameters/Page"
        - $ref: "#/components/parameters/Size"
        - in: query
          name: nomor_sales_order
          schema:
            type: string

      responses:
        "200":
          $ref: "#/components/responses/200"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"        